services:
  audio-processor:
    build: .
    container_name: PiAudio
    privileged: true
    network_mode: host
    devices: 
      - /dev/snd
    volumes:
      - ./config/asound.conf:/etc/asound.conf:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /etc/machine-id:/etc/machine-id:ro
      - ./app:/app

      - ./pulse:/etc/pulse:ro
      - ./config/bluez-main.conf:/etc/bluetooth/main.conf:ro
      - ./config/pulseaudio.conf:/etc/dbus-1/system.d/pulseaudio.conf:ro
    environment:
      - PULSE_RUNTIME_PATH=/run/pulse
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket