services:
  audio-processor:
    build: .
    container_name: PiAudio
    privileged: true
    network_mode: host
    pid: host
    devices: 
      - /dev/snd
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - ./config/asound.conf:/etc/asound.conf:ro
      - /run/dbus:/run/dbus
      #- /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      #- /run/user/1000/pulse:/run/user/1000/pulse
      #- ./pulse:/etc/pulse
      - ./config/bluez-main.conf:/etc/bluetooth/main.conf:ro
    environment:
        XDG_RUNTIME_DIR: /tmp/xdg
        PULSE_SERVER: unix:/tmp/xdg/pulse/native