services:
  audio-processor:
    build: .
    container_name: PiAudio
    privileged: true
    network_mode: host
    pid: host
    devices:
      - /dev/snd
    volumes:
      - ./app:/app
      - /etc/machine-id:/etc/machine-id:ro
      - ./config/asound.conf:/etc/asound.conf:ro
      - ./config/bluez-main.conf:/etc/bluetooth/main.conf:ro
      - /run/dbus:/run/dbus
      - /run/user/1000/pulse:/run/user/1000/pulse                   # <-- host PulseAudio socket
      #- /home/pi/.config/pulse/cookie:/home/audiouser/.config/pulse/cookie:ro
      - /home/pi/.config/pulse/cookie:/tmp/pulse-cookie:ro  # <-- cookie auth

    environment:
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      user: "1000:1000"  # Match host user so you can access /run/user/1000
      

      